### ISSUE TITLE
Devportal making request to api manager returns 404 HTTP Status

### ISSUE THREAD

**Issue by aqp696** [apiman/apiman-developer-portal#9] opened 2020-10-24 17:32 UTC
# Description
I have installed and working apiman manager 2.0.0.Final and apiman-gateway vert.x 2.0.0.Final. After login successfully to the the apiman developer portal,  it shows the next toast notification:
![image](https://user-images.githubusercontent.com/1755312/97088053-ad7eb100-162e-11eb-8c81-d53ace0b274e.png)
# Investigation
It makes a call to the apiman manager in the endpoint /apiman/developers which does not exist. Currently my apiman manager serves under /apimanui/api-manager. I did not see in the docs more information about this I don't know if it's a bug or not.
Thanks in advance

**Comment by volkflo** [comment] 2020-10-26 08:16
Hi @aqp696,

Thanks for reporting this, but it is not a bug :)
The developer portal backend is not included in the apiman 2.0.0 release, it will be part of the upcoming 2.1.0 release. 

If you want to try the developer portal you have to build the current master of apiman by yourself: https://github.com/apiman/apiman#quickstart-ie-how-to-run-it

**Closed** 2020-10-28 10:16 UTC
Labels: question

**Comment by bekihm** [comment] 2020-10-30 11:13
@aqp696 Cool that you will try out the Developer Portal :-)
Does it now work with the master branch or do you wait for the 2.1.0 release?

**Comment by aqp696** [comment] 2020-10-31 00:13
> @aqp696 Cool that you will try out the Developer Portal :-)
> Does it now work with the master branch or do you wait for the 2.1.0 release?

Hi @bekihm I am waiting for the 2.1.0 release XDD. I found so many problems making it work Apiman with the vertx gateway with my own Keycloak ... in part due to the lack of updated documentation (pointing to previous releases), finding solutions in closed issues of the Apiman repository etc. Now I have a fully functional Apiman with several apis behind it and in the future 2.1.0 release I will integrate this developer portal.

Anyway, I keep an eye on you guys. Kudos for this fantastic open source project. A must have in the ecosystem of Apiman.
